
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 13 17:38:03 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 12;
  public static final int CONST = 6;
  public static final int CHAR = 9;
  public static final int NAMESPACE = 48;
  public static final int NOT_EQUAL = 31;
  public static final int GREATER = 38;
  public static final int LPAREN = 33;
  public static final int CONTINUE = 25;
  public static final int FOR = 44;
  public static final int LESS = 35;
  public static final int MINUS = 16;
  public static final int STATIC = 29;
  public static final int RPAREN = 28;
  public static final int SEMICOLON = 7;
  public static final int AND = 20;
  public static final int RANGE = 47;
  public static final int OR = 19;
  public static final int BOOL = 10;
  public static final int COMMA = 11;
  public static final int CLASS = 49;
  public static final int INC = 17;
  public static final int DIV = 30;
  public static final int LESS_EQUAL = 40;
  public static final int PLUS = 27;
  public static final int ASSIGN = 14;
  public static final int IF = 21;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int RBRACKET = 13;
  public static final int EQUAL = 34;
  public static final int GREATER_EQUAL = 39;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 37;
  public static final int MOD = 36;
  public static final int NUMBER = 8;
  public static final int BREAK = 24;
  public static final int IDENT = 3;
  public static final int VOID = 15;
  public static final int ARROW = 32;
  public static final int COLON = 43;
  public static final int LBRACE = 4;
  public static final int ELSE = 22;
  public static final int READ = 41;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 45;
  public static final int DEC = 18;
  public static final int PRINT = 42;
}

