
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 12 00:25:58 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 12;
  public static final int CONST = 6;
  public static final int CHAR = 9;
  public static final int NAMESPACE = 44;
  public static final int NOT_EQUAL = 27;
  public static final int CONTINUE = 47;
  public static final int GREATER = 40;
  public static final int LPAREN = 31;
  public static final int LESS = 33;
  public static final int FOR = 17;
  public static final int MINUS = 26;
  public static final int STATIC = 19;
  public static final int RPAREN = 18;
  public static final int SEMICOLON = 7;
  public static final int AND = 30;
  public static final int RANGE = 36;
  public static final int OR = 48;
  public static final int BOOL = 10;
  public static final int COMMA = 11;
  public static final int CLASS = 45;
  public static final int INC = 39;
  public static final int DIV = 25;
  public static final int LESS_EQUAL = 42;
  public static final int PLUS = 16;
  public static final int ASSIGN = 14;
  public static final int IF = 23;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int RBRACKET = 13;
  public static final int EQUAL = 32;
  public static final int GREATER_EQUAL = 41;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 35;
  public static final int NUMBER = 8;
  public static final int MOD = 34;
  public static final int BREAK = 37;
  public static final int IDENT = 3;
  public static final int VOID = 29;
  public static final int ARROW = 28;
  public static final int COLON = 15;
  public static final int LBRACE = 4;
  public static final int ELSE = 22;
  public static final int READ = 38;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 20;
  public static final int DEC = 49;
  public static final int PRINT = 43;
}

