
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 16 21:12:22 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 8;
  public static final int CHAR = 41;
  public static final int CONST = 5;
  public static final int NAMESPACE = 48;
  public static final int NOT_EQUAL = 27;
  public static final int LPAREN = 29;
  public static final int GREATER = 34;
  public static final int CONTINUE = 21;
  public static final int FOR = 44;
  public static final int LESS = 31;
  public static final int MINUS = 12;
  public static final int STATIC = 25;
  public static final int RPAREN = 24;
  public static final int SEMICOLON = 6;
  public static final int AND = 16;
  public static final int RANGE = 47;
  public static final int OR = 15;
  public static final int BOOL = 42;
  public static final int COMMA = 7;
  public static final int CLASS = 49;
  public static final int INC = 13;
  public static final int DIV = 26;
  public static final int LESS_EQUAL = 36;
  public static final int PLUS = 23;
  public static final int ASSIGN = 10;
  public static final int IF = 17;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int RBRACKET = 9;
  public static final int EQUAL = 30;
  public static final int GREATER_EQUAL = 35;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 33;
  public static final int NUMBER = 40;
  public static final int MOD = 32;
  public static final int IDENT = 43;
  public static final int BREAK = 20;
  public static final int VOID = 11;
  public static final int ARROW = 28;
  public static final int COLON = 39;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int READ = 37;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 45;
  public static final int DEC = 14;
  public static final int PRINT = 38;
}

